### PR TITLE
Fix if using state.path as radioInput's name

### PR DESCRIPTION
**Pull request by pablohirafuji**

### CODE REVIEW

**Comment by etaque** [comment]
Hi, I need a bit more context on this. What problem does it solve?

**Comment by pablohirafuji** [comment]
Hi! Sorry, I was in a hurry when I made these. I should have waited until I had some more time. Sorry for the inconvenience.

This is related with [this](https://github.com/etaque/elm-simple-form/pull/47/commits) pull request. It's a fix of the example in case that pull request was accepted.

What that pull request does is a change on the radioInput's attributes. Now, it's setting the `name` attribute as the `value` argument. For the `radio` input work as a group, like when I select one, deselect the others, the `name` attribute of the entire group has to be the same.

So my proposal is to use the `state.path` as the `name` attribute, so it's the same for the entire group of radio's input for that specific field, and set the `value` attribute using the `value` argument.

**Comment by pablohirafuji** [comment]
I believe that there is no need to worry about name collision, as each `<form>` manages its input independently. [Demo](http://codepen.io/pablohirafuji/pen/ORaGow?editors=1000).

**Comment by etaque** [comment]
Okey, the original implementation was definitely bugged. Thanks for taking the time to explain.

**Pull request merged**
