### PR TITLE
Alpha upgrade

### PR DESCRIPTION
**Pull request by stephenreddek**
Still working on the examples and the tests.

### CODE REVIEW

**Comment by stephenreddek** [comment]
run tests with the command: `./node_modules/.bin/elm-test --compiler _ELM_19_LOCATION_`

**Comment by stephenreddek** [comment]
Writing the quick date parser made me wonder if it would be helpful to have a builtin parser validation function (similar to the regex one). It would essentially wrap this:

```
customValidation string (Parser.run parser >> Result.mapError (always e))
```

where `parser` and `e` are the two parameters to the validation function

**Comment by etaque** [comment]
Hi @stephenreddek, this is looking good to me, also thanks for the Travis fix! Do you have anything left in mind, or shall I merge & publish?

**Comment by stephenreddek** [comment]
I can't think of anything else! I remember we talked about removing the test helpers so that there wasn't a dependency on `elm-explorations/test` in prod, but I think this is all that's required for 0.19. I've clicked around in the examples, but I haven't done an in-depth testing of each feature.

**Comment by stephenreddek** [comment]
I noticed I hadn't updated the code in the README, so I did that as well. Let me know if there's anything else I should update in there!

**Comment by etaque** [comment]
Regarding test helpers, i tend to agree that `elm-explorations/test` shouldn't live in prod dependencies. Let's extract them into a dedicated package ; I can host it but I don't feel like I would be the best maintainer as I don't use them. Would you be interested in hosting it @stephenreddek ? Also pinging @dimbleby who was the initial commiter.

**Comment by dimbleby** [comment]
I'm not clear what I'm being asked, but I no longer maintain any Elm code.  So

* if it was "hey, what do you think of this?" then: I don't know, but I'm sure I don't want to stand in the way of progress, please carry on
* if it was "would you like to own some new extracted package?" then: no, I am not interested in doing that.

Cheers!

**Comment by etaque** [comment]
Ok @dimbleby! Cheers.

**Comment by stephenreddek** [comment]
@etaque I also do not use them, so I don't think I would be a good maintainer either. I see that they were added in PR #91. @dillonkearns do you have any thoughts on this?

The other reason I see for moving it to another package is that right now elm-form requires the package users to use its version of elm-test in order to use the forms at all. This was an issue for my team when we were attempting to just install the bug fixes from 2.1.0 but were behind a version of elm-test.

**Comment by etaque** [comment]
All right, I'll extract and host the test helpers after merge.

**Comment by aecay** [comment]
Hi @etaque, just wondering what the status of the 0.19 upgrade is?  I see that this PR is merged, but the new version isn't published to the elm package repo yet...

(PS thanks for this package, it's very helpful!  :smiley:)

**Comment by etaque** [comment]
Hi, it's coming! Just need to allocate a slot of time for this. Thanks for the kind words.

**Comment by etaque** [comment]
Package published. Let me know how it goes for you. Big thanks to @stephenreddek for all the work done on this upgrade!

**Comment by stephenreddek** [comment]
Thank you @etaque ! Are you still planning to pull out the `Test` package in a later release?

**Comment by etaque** [comment]
Yes, but there is a circular dependency (lib needs tests needs lib) so I needed to publish it with `Test` first.

**Comment by aecay** [comment]
@etaque thanks for the update!  Now my app is fully upgraded to 0.19 with elm-form from the official package repo.  :+1:

**Pull request merged**
