### PR TITLE
Add helper functions for testing validations with example test suite.

### PR DESCRIPTION
**Pull request by dillonkearns**
Hello @etaque, thanks for the awesome package. It would be nice to have some helper functions to test individual validations. I'd welcome any suggestions if you see any opportunities for improvement!

### CODE REVIEW

**Comment by etaque** [comment]
Hi @dillonkearns, that's an interesting PR! Let me find a bit of time to review it first.

**Comment by dillonkearns** [comment]
Sounds good, thank you for the update!

**Comment by etaque** [comment]
All good, thanks, nice addition.

**Comment by dillonkearns** [comment]
Awesome, thanks @etaque I'm very happy to see this merged in!

**Pull request merged**
